# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Previous version test, round 1

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Start test
        run: |
          cd runner
          python3 game_runner.py 1x3_v 10 50
